name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x, 15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Setup Config
        env:
          # 應當放到secret內
          API_URL: ${{ secrets.API_URL }}
        run: |
          echo "export const API_URL = '$API_URL'" > ./src/configs/api.js
          echo "cat ./src/configs/api.js"
          cat ./src/configs/api.js
          
      - name: Install & Build # 執行指令
        run: |
          npm install
          npm run build
  
